#define globalDefine_render_highlightedEntity 1
#define globalDefine_render_DrawLifePoints 1
#define globalDefine_particles_EulerianGrid 0
#define globalDefine_particles_Drawing 0
#define globalDefine_render_camera_cameraZ 1
#define globalDefine_render_cameraZStep 6.0f
#define globalDefine_render_chunksoutline 0
#define globalDefine_simulation_showAttributes_standard 1
#define globalDefine_simulation_showAttributes_special 1

#define globalDefine_server_network_sequenceNumber 0
#define globalDefine_server_test 1
#define globalDefine_server_testing 1
#define globalDefine_server_testing2 1
#define globalDefine_server_testing3 1.0f
#define globalDefine_server_spawnTree 0